### ISSUE TITLE
[Feature Request] config to control how many number of unique blocks can be placed in the four quadrants

### ISSUE THREAD

**Issue by Landiie** [breakinblocks/Plonk#4]
Sorry if the title is a tad confusing, but what i mean is, this: there are four quadrants per block face that can store items, but i noticed that each quadrant can store 64 of each item in it, leading to 4 stacks of 64 occupied in one space. I was wondering if there could be a config to control this value, like 32 per each quadrant or 16, or whatever number specified. I think it could really help pack devs. Saying this because i planned to have a feature using this mod, however it would be unbalanced for the style of pack im going for.

Just a thought!

**Comment by BlueAgent** [comment]
Was a bit on the fence about this since we do want the mod to be consistent (was why older versions of the mod retroactively no longer get washed away by water with the waterlogging feature in 1.13+). After a bit of thought and discussion this does seem like a good idea to add since it could be of use in modpacks that extend the early game before normal chests are available.

**Comment by Landiie** [comment]
for sure! It is your choice after all, but since i am an avid packmaker myself i thought this would be good to bring up. Thanks again <3

**Comment by BlueAgent** [comment]
Feature is now available in the latest versions of Plonk.

In 1.7.10 and 1.12.2 the config can be found in `config/plonk.cfg`.

For 1.16.3 it can be found in `<world>/serverconfig/plonk-server.toml`.
