### ISSUE TITLE
Conduits, beds, banners and shields render strangely

### ISSUE THREAD

**Issue by k1r0s** [breakinblocks/Plonk#7]
Shields are not properly displayed (1.12 although It might be on any version)

**Comment by BlueAgent** [comment]
Oh geez, seems like this is going to be an interesting one to fix.

Plonk uses a [heuristic](https://github.com/breakinblocks/Plonk/blob/4bae2b0330a05c75e1bb14db2043b3522f7449cc/src/main/java/com/breakinblocks/plonk/client/render/tile/TESRPlacedItems.java#L45-L68) to determine if it should be rendered as a normal item or as a block but it's far from perfect. The way vanilla item frames work is that each item has an associated camera transform for rendering in an item frame. Since it's not feasible to have each item (vanilla and potentially modded) to have a camera transform for plonk, a heuristic is needed to detect what renders "like a block" and then plonk applies a transformation before using the item frame rendering.

After going through the vanilla items list, seems like conduits, beds, banners and shields render strangely. (Although the banner one is kinda neat, maybe there should be a way to manually select the render type for such situations that the heuristic fails or for cosmetic reasons...)
![2020-12-07_19 16 54](https://user-images.githubusercontent.com/630920/101344739-e615d980-38c0-11eb-8018-55db0804f2b5.png)

**Comment by BlueAgent** [comment]
Fortunately not an issue in 1.7.10 since beds use a sprite and there's no conduits, banners and shields.

**Comment by BlueAgent** [comment]
Found some time / motivation to look into this interesting problem.
![2020-12-15_23 54 22](https://user-images.githubusercontent.com/630920/102239681-12b99900-3f32-11eb-98fa-c8da0b49d1f7.png)
So banners stick out a bit and so do dragon heads. Not too sure how to address these without more special casing, but this should be okay for now.
I'm thinking of adding the ability to flip between render types for cosmetic purposes as the banners before this fix were kinda neat.
For now though I'm gonna consider this fixed for the next release, will close once it's out.
Let me know if you got some ideas.

**Comment by BlueAgent** [comment]
Fixed with the release of [Plonk v9.0.4 (mc 1.16.4)](https://www.curseforge.com/minecraft/mc-mods/plonk/files/3155184).
Happy new years! :3
